language: bash
sudo: required
before_install:
  - sudo make dependencies
install:
  - sudo chown -R travis:travis /home/travis/.cpanm
  - make local-libs
script:
  - export PACKAGE=`perl -ne 'print $1 if /^Package:\s+(.+)/;' < debian/control`
  - export TEST_URL=app.psgi
  - prove -l -Ilocal/lib/perl5 -v
  - make release-file
  - sudo dpkg -i ${PACKAGE}_*.deb
  - sudo service ${PACKAGE} status
  - sudo service ${PACKAGE} restart
  - export TEST_URL=deployed
  - prove -l -v
cache: apt
after_failure:
  - tail -200 /var/log/${PACKAGE}/error.log
  - tail -200 /var/log/${PACKAGE}/access.log
  - curl -i http://localhost:6013/ 
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying $RELEASE_PKG_FILE"
