#!/usr/bin/perl
use v5.14;

foreach (@ARGV) {
    system("./app/getzdb.pl $_");
    system("./app/getlobid.pl $_");
    system("./app/getopac.pl $_");
    system("./app/txt2ttl.pl isil/$_/sites.txt > isil/$_/sites.ttl");
    system("./app/zdb2ttl.pl isil/$_/zdb.pica > isil/$_/zdb.ttl");
}
