#!/usr/bin/perl
use v5.14;

foreach (@ARGV) {
    system("./bin/getzdb.pl $_");
    system("./bin/getlobid.pl $_");
    system("./bin/getopac.pl $_");
    system("./bin/txt2ttl.pl isil/$_/sites.txt > isil/$_/sites.ttl");
    system("./bin/zdb2ttl.pl isil/$_/zdb.pica > isil/$_/zdb.ttl");
}
