TITLE   = VZG-Standortverwaltung
AUTHOR  = Jakob Voß (VZG)
NAME    = libsites

include vzgspec/Makefile

# TODO move to makespec/vzgspec
TEX_VARS = -V documentclass=scrreprt --include-in-header=$(MAKESPEC)/gbvstyle.tex
LANGUAGE=ngerman
DATE += "\(version $(VERSION)\)"
