.TH "LIBSITES" "1" "" "Manual" ""
.SH GBV\-Standortverzeichnis (libsites)
.PP
Dieses git\-Repository enthält eine Webanwendung zum Betrieb des
GBV\-Standortverzeichnis.
Die eigentlichen informationen zu Standorten von Bibliotheken, Museen
und verwandten Einrichtungen sowie Skripte zur Aggregation dieser
Informationen befinden sich dagegen im Repository
libsites\-config (https://github.com/gbv/libsites-config).
.SS Technical requirements
